import Head from "next/head";
import {BsFillMoonStarsFill,BsYoutube,} from "react-icons/bs";
import {AiFillMediumSquare, AiFillTwitterSquare,} from "react-icons/ai";
import Image from "next/image";
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import {useState} from "react";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Christmas React Study</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-16 md:px-20 lg:px-40 dark:bg-gray-900 dark:text-white">  
        <section className="min-h-screen">
          <nav className="py-16 mb-12 flex justify-between">
            <h1 className=" text-xl font-burtons">createdby</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}className=" cursor-pointer text-2xl"/>
                </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
                </li>
            </ul>
          </nav>
          <div className=" text-center p-8">
            <h2 className=" text-5xl py-4 text-teal-700 font-bold md:text-6xl">Yoon Ro</h2>
            <h3 className="text-2xl py-4 font-medium md:text-3xl">UX designer and Developer</h3>
            <p className="text-md text-gray-800 md:text-xl max-w-xl mx-auto  dark:text-white">Freelancer providing services for programming and design content needs. Freelancer providing services for programming and design content needs. Freelancer providing services for programming and design content needs.</p>
          </div>
          <div className="flex justify-center gap-16 py-8 text-5xl">
           <BsYoutube className=" fill-orange-500"/>
           <AiFillTwitterSquare className=" fill-red-300"/>
           <AiFillMediumSquare className="fill-teal-500"/>
          </div>

          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-8 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover"/>
          </div>
        </section>
        
        <section>
          <div>
            <h3 className="text-2xl py-1 font-medium mt-16">Sevices I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800  dark:text-white">
              Since the beginning of my journey as a freelance developer. <span className="text-teal-500 font-medium">Colour Text</span> is pretty cool. Since the beginning of my journey as a freelance developer. <span className="text-teal-600">Colour Text</span> is pretty cool.
            </p>
          </div>
          
          <div className="md:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-2xl my-10 dark:bg-white">
            <Image src={design} width={100} height={100}/>
            <h3 className="text-lg font-medium pt-8 pb-2 text-gray-800">Beautiful Designs</h3>
            <p className="py-2 text-gray-800">Creating elegant designs uited for your needs following core design theory.</p>
            <h4 className="py-4 text-teal-600">Design tools I use</h4>
            <p className="text-gray-800 py-1 ">Photoshop</p>
            <p className="text-gray-800 py-1 ">Illustrator</p>
            <p className="text-gray-800 py-1 ">Figma</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-2xl my-10 dark:bg-white">
            <Image src={code} width={100} height={100}/>
            <h3 className="text-lg font-medium pt-8 pb-2 text-gray-800">Beautiful Designs</h3>
            <p className="py-2 text-gray-800">Creating elegant designs uited for your needs following core design theory.</p>
            <h4 className="py-4 text-teal-600">Design tools I use</h4>
            <p className="text-gray-800 py-1 ">Photoshop</p>
            <p className="text-gray-800 py-1 ">Illustrator</p>
            <p className="text-gray-800 py-1 ">Figma</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-2xl my-10 dark:bg-white">
            <Image src={consulting} width={100} height={100}/>
            <h3 className="text-lg font-medium pt-8 pb-2 text-gray-800">Beautiful Designs</h3>
            <p className="py-2 text-gray-800">Creating elegant designs uited for your needs following core design theory.</p>
            <h4 className="py-4 text-teal-600">Design tools I use</h4>
            <p className="text-gray-800 py-1 ">Photoshop</p>
            <p className="text-gray-800 py-1 ">Illustrator</p>
            <p className="text-gray-800 py-1 ">Figma</p>
            </div>
          </div>

        </section>
          <div>
            <h3 className="text-2xl py-1 font-medium">Portfolio</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap"> 
          <div className="basis-1/3 flex-1">
            <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"></Image>
          </div>
          <div className="basis-1/3 flex-1">
            <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"></Image>
          </div>
          <div className="basis-1/3 flex-1">
            <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"></Image>
          </div>
          <div className="basis-1/3 flex-1">
            <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"></Image>
          </div>
          <div className="basis-1/3 flex-1">
            <Image src={web5} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"></Image>
          </div>
          <div className="basis-1/3 flex-1">
            <Image src={web6} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"></Image>
          </div>
          </div>

      </main>
    </div>
  );
}
