import Head from "next/head";
import {BsFillMoonStarsFill,BsYoutube} from "react-icons/bs";

export default function Home() {

  return (
    <div>
      <Head>
        <title>Christmas React Study</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-16">  
        <section className="min-h-screen">
          <nav className="py-16 mb-12 flex justify-between">
            <h1 className=" text-xl font-burtons">developedby</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className=" cursor-pointer text-2xl"/>
                </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
                </li>
            </ul>
          </nav>
          <div className=" text-center p-8">
            <h2 className=" text-5xl py-4 text-teal-700 font-bold">Yoon Ro</h2>
            <h3 className="text-2xl py-4 font-medium">UX designer and Developer</h3>
            <p className="text-md text-gray-800">Freelancer providing services for programming and design content needs.</p>
          </div>
          <div className="flex justify-center gap-16 py-8 text-5xl">
           <BsYoutube className=" fill-orange-500"/>
           <BsYoutube className=" fill-red-300"/>
           <BsYoutube className="fill-teal-500"/>
          </div>
        </section>
      </main>
    </div>
  );
}
